### ISSUE TITLE
Help display closes quickly after it is shown and difficult to read

### ISSUE THREAD

**Issue by jamesobutler** [fsemerar/SlicerTomoSAM#4]
I was having difficulties reading the help information upon pressing the "Help" button in the TomoSAM module. Pressing near the bottom of the button causes the display to show up momentarily and then close before I have time to read it.

https://github.com/fsemerar/SlicerTomoSAM/blob/426bd5422b5fe643db677f237f5acae5a6be0d42/TomoSAM/tomosam.py#L561-L562

Maybe just having the text in the general Help section of the module would be better rather in this pop-up that is difficult to read since it disappears quickly.
![image](https://github.com/fsemerar/SlicerTomoSAM/assets/15837524/9d2fc1e5-cf68-420e-b743-5c990492252e)

Below shows the help display closing quickly upon pressing the "Help" button resulting in being very difficult to read the content.

https://github.com/fsemerar/SlicerTomoSAM/assets/15837524/6ab90858-385c-42d1-8b99-a172c90277fc

**Comment by fsemerar** [comment]
Thank you for your feedback, I will change this now. It will be up for the next build

**Comment by jamesobutler** [comment]
For reference this issue was closed by https://github.com/fsemerar/SlicerTomoSAM/commit/344d18f62940731714f246ccd82bc9309ff714c2.
