### ISSUE TITLE
Would be nice to have sample data

### ISSUE THREAD

**Issue by pieper** [fsemerar/SlicerTomoSAM#7]
For people who want to test the module it would be helpful to be able to easily download a sample dataset that is known to work.  This would let people check their installation and GPU without questions about whether the data is appropriate.

**Comment by fsemerar** [comment]
As noted in the README, we have this at [this link](https://nasa-ext.box.com/s/gyjlrhv63pdj2k9yip6g5reb2r9jlc6l)
