### ISSUE TITLE
Failed to download 3D Slicer 5.2.2

### ISSUE THREAD

**Issue by thkarag** [fsemerar/SlicerTomoSAM#8]
When I try to download TomoSAM from the extensions installer, I get the error:

Download of extension failed, could not find an extension with id = 64a40db8b81c954f3399b015

**Comment by fsemerar** [comment]
I had that happen to me as well, I fixed it by downloading a fresh Slicer installer and reinstalling it. Would you give that a try?

**Comment by pieper** [comment]
I eventually go it to work without needing to reinstall Slicer, just retrying.  Do you know why it doesn't work reliably?
